###
GET http://localhost:8080/api/v1/solicitude
Accept: application/json
token: 0

###
POST http://localhost:8080/api/v1/solicitude
Accept: application/json
Content-Type: application/json

{
  "subjectCode": "CHEM",
   "personId": 3,
  "recurrent": true,
  "startDate": "2023-11-01",
    "endDate": "2023-12-31",
    "periods": [31],
    "spaceId": 53
}
###
PUT http://localhost:8080/api/v1/solicitude/302/reject
token: 1
Accept: application/json

###
PUT http://localhost:8080/api/v1/solicitude/354/approve
token: 1
Accept: application/json