###
GET http://localhost:8080/api/v1/solicitude
Accept: application/json
token: 1 

###
POST http://localhost:8080/api/v1/solicitude
Accept: application/json
Content-Type: application/json

{
  "subjectCode": "CHEM",
   "personId": 3,
  "recurrent": true,
  "startDate": "2023-11-19",
    "endDate": "2023-12-25",
    "periods": [37, 38],
    "spaceId": 10
}
###